classDiagram
    namespace Models {
        class User
        class Post
    }

    namespace Services {
        class UserService
        class PostService
    }

    UserService --> User
    PostService --> Post
